"""Error pattern diagnosis for remediation failures.

This module identifies known ffmpeg error patterns from stderr output and produces
structured diagnostics with human-readable messages and optional recovery strategies.
Each diagnosis distinguishes whether the problematic file was the user's original
input or an intermediate file produced by the processing pipeline.
"""

from __future__ import annotations

import logging
import os
import platform
import re
import subprocess
from dataclasses import dataclass
from enum import Enum
from typing import List, Optional

logger = logging.getLogger(__name__)


class FileOrigin(Enum):
    """Whether a file was provided by the user or generated by the pipeline."""

    USER_INPUT = "user_input"
    PIPELINE_INTERMEDIATE = "pipeline_intermediate"


@dataclass
class ErrorPattern:
    """A known ffmpeg error pattern with diagnosis metadata.

    Attributes:
        regex: Regex pattern to match against ffmpeg stderr.
        diagnosis_template: Pattern-specific diagnosis fragment (no origin context).
        suggested_fix: Suggested fix for the user.
        recovery_strategy: Name of recovery strategy (e.g., "skip_metadata",
            "re_encode", "ignore_errors", "genpts", "re_encode_codec") or None.
        typical_origin: Which origin this error typically comes from, or None
            if it can come from either.
    """

    regex: str
    diagnosis_template: str
    suggested_fix: str
    recovery_strategy: Optional[str] = None
    typical_origin: Optional[FileOrigin] = None


@dataclass
class Diagnosis:
    """Result of diagnosing an ffmpeg error.

    Attributes:
        pattern: The matched error pattern, or None for unknown errors.
        diagnosis: The fully rendered diagnosis message including origin context.
        suggested_fix: The suggested fix for the user.
        file_path: Path to the problematic file.
        file_origin: Whether the file is user input or pipeline intermediate.
        recovery_strategy: Recovery strategy name if available.
    """

    pattern: Optional[ErrorPattern]
    diagnosis: str
    suggested_fix: str
    file_path: str
    file_origin: FileOrigin
    recovery_strategy: Optional[str]


ERROR_PATTERNS: List[ErrorPattern] = [
    ErrorPattern(
        regex=r"moov atom not found",
        diagnosis_template="has a corrupt or incomplete container (moov atom not found).",
        suggested_fix="Re-download or re-encode the input file to ensure the container is complete.",
        recovery_strategy="skip_metadata",
        typical_origin=FileOrigin.USER_INPUT,
    ),
    ErrorPattern(
        regex=r"Invalid data found when processing input",
        diagnosis_template="appears to be corrupt or truncated (invalid data found when processing input).",
        suggested_fix="Re-download or re-encode the input file. If the file plays in a media player, try converting it with ffmpeg first.",
        recovery_strategy="ignore_errors",
        typical_origin=None,
    ),
    ErrorPattern(
        regex=r"non-existing PPS referenced|decode_slice_header error|no frame",
        diagnosis_template="contains corrupt H.264 video frames.",
        suggested_fix="Re-encode the input file with a fresh H.264 encode to fix corrupt frames.",
        recovery_strategy="ignore_errors",
        typical_origin=None,
    ),
    ErrorPattern(
        regex=r"Non-monotonous DTS",
        diagnosis_template="has disordered timestamps (non-monotonous DTS).",
        suggested_fix="Re-mux the input file to fix timestamp ordering, e.g.: ffmpeg -i input.mp4 -c copy -output.mp4",
        recovery_strategy="genpts",
        typical_origin=None,
    ),
    ErrorPattern(
        regex=r"Could not write header|incorrect codec parameters",
        diagnosis_template="has a codec mismatch or incompatible codec parameters for the output container.",
        suggested_fix="Try a different output format or re-encode the input file to a more compatible codec.",
        recovery_strategy="re_encode_codec",
        typical_origin=FileOrigin.PIPELINE_INTERMEDIATE,
    ),
    ErrorPattern(
        regex=r"No space left on device",
        diagnosis_template="could not be processed because the disk is full.",
        suggested_fix="Free up disk space and try again.",
        recovery_strategy=None,
        typical_origin=None,
    ),
    ErrorPattern(
        regex=r"Permission denied",
        diagnosis_template="could not be accessed due to a permission error.",
        suggested_fix="Check file and directory permissions and try again.",
        recovery_strategy=None,
        typical_origin=None,
    ),
    ErrorPattern(
        regex=r"PES packet size mismatch",
        diagnosis_template="has transport stream corruption (PES packet size mismatch).",
        suggested_fix="Re-mux the transport stream or re-encode the input file.",
        recovery_strategy="ignore_errors",
        typical_origin=FileOrigin.USER_INPUT,
    ),
    ErrorPattern(
        regex=r"Unknown encoder|Encoder .* not found",
        diagnosis_template="requires a codec that is not available in your ffmpeg installation.",
        suggested_fix="Install the required codec or use a different ffmpeg build with the needed encoder support.",
        recovery_strategy=None,
        typical_origin=None,
    ),
    ErrorPattern(
        regex=r"Empty output file",
        diagnosis_template="produced an empty output file.",
        suggested_fix="This is detected separately via check_output_file.",
        recovery_strategy=None,
        typical_origin=FileOrigin.PIPELINE_INTERMEDIATE,
    ),
]


def _build_origin_prefix(file_origin: FileOrigin, file_path: str) -> str:
    """Build the origin-specific prefix for a diagnosis message."""
    if file_origin == FileOrigin.USER_INPUT:
        return f"Your original input file '{file_path}'"
    return f"An intermediate file produced by video-censor-personal ('{file_path}')"


def _build_origin_suffix(file_origin: FileOrigin) -> str:
    """Build the origin-specific suffix for a diagnosis message."""
    if file_origin == FileOrigin.PIPELINE_INTERMEDIATE:
        return " This is likely a bug in our processing pipeline."
    return ""


def diagnose_error(
    stderr: str, file_path: str, file_origin: FileOrigin
) -> Diagnosis:
    """Diagnose an ffmpeg error from its stderr output.

    Iterates through known error patterns and returns a structured diagnosis
    for the first match. If no pattern matches, returns a generic diagnosis
    with the raw stderr.

    Args:
        stderr: The stderr output from the failed ffmpeg process.
        file_path: Path to the file that caused the error.
        file_origin: Whether the file is a user input or pipeline intermediate.

    Returns:
        A Diagnosis with the matched pattern, rendered message, and recovery
        strategy (if available).
    """
    for pattern in ERROR_PATTERNS:
        if re.search(pattern.regex, stderr, re.IGNORECASE):
            prefix = _build_origin_prefix(file_origin, file_path)
            suffix = _build_origin_suffix(file_origin)
            diagnosis_msg = f"{prefix} {pattern.diagnosis_template}{suffix}"
            logger.debug(
                "Matched error pattern %r for file %s (origin=%s)",
                pattern.regex,
                file_path,
                file_origin.value,
            )
            return Diagnosis(
                pattern=pattern,
                diagnosis=diagnosis_msg,
                suggested_fix=pattern.suggested_fix,
                file_path=file_path,
                file_origin=file_origin,
                recovery_strategy=pattern.recovery_strategy,
            )

    logger.debug(
        "No known error pattern matched for file %s (origin=%s), stderr: %s",
        file_path,
        file_origin.value,
        stderr[:500],
    )
    prefix = _build_origin_prefix(file_origin, file_path)
    suffix = _build_origin_suffix(file_origin)
    diagnosis_msg = f"{prefix} encountered an unrecognized error.{suffix}\n\nffmpeg stderr:\n{stderr}"
    return Diagnosis(
        pattern=None,
        diagnosis=diagnosis_msg,
        suggested_fix="Check the ffmpeg stderr output above for details. If the problem persists, please report this as a bug.",
        file_path=file_path,
        file_origin=file_origin,
        recovery_strategy=None,
    )


def check_output_file(path: str) -> Optional[Diagnosis]:
    """Check whether an output file exists and is non-empty.

    Args:
        path: Path to the output file to check.

    Returns:
        A Diagnosis if the file is missing or empty, or None if the file
        is valid.
    """
    if not os.path.exists(path):
        logger.warning("Output file does not exist: %s", path)
        return Diagnosis(
            pattern=None,
            diagnosis=(
                f"An intermediate file produced by video-censor-personal ('{path}') "
                "was expected but does not exist. "
                "This is likely a bug in our processing pipeline."
            ),
            suggested_fix="Re-run the processing. If this persists, please report it as a bug.",
            file_path=path,
            file_origin=FileOrigin.PIPELINE_INTERMEDIATE,
            recovery_strategy=None,
        )

    if os.path.getsize(path) == 0:
        logger.warning("Output file is empty (0 bytes): %s", path)
        return Diagnosis(
            pattern=None,
            diagnosis=(
                f"An intermediate file produced by video-censor-personal ('{path}') "
                "is empty (0 bytes). "
                "This is likely a bug in our processing pipeline."
            ),
            suggested_fix="Re-run the processing. If this persists, please report it as a bug.",
            file_path=path,
            file_origin=FileOrigin.PIPELINE_INTERMEDIATE,
            recovery_strategy=None,
        )

    return None


def generate_bug_report(
    phase: str,
    error_msg: str,
    file_path: str,
    command: str,
    config_file: str,
    input_file: str,
) -> str:
    """Generate a copy-pasteable GitHub issue report for a pipeline bug.

    Args:
        phase: The processing phase where the error occurred.
        error_msg: The full error message or stderr output.
        file_path: Path to the problematic file.
        command: The command that was run.
        config_file: Path to the configuration file used.
        input_file: Path to the original input file.

    Returns:
        A formatted string suitable for pasting into a GitHub issue.
    """
    try:
        result = subprocess.run(
            ["ffmpeg", "-version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        ffmpeg_version = result.stdout.splitlines()[0] if result.stdout else "unknown"
    except (FileNotFoundError, subprocess.TimeoutExpired, IndexError):
        ffmpeg_version = "unknown"

    os_info = platform.platform()
    python_version = platform.python_version()

    error_lines = error_msg.strip().splitlines()
    first_three_lines = "\n".join(error_lines[:3])
    error_summary = error_lines[0][:60] if error_lines else "unknown error"

    separator = "─" * 56

    return (
        f"{separator}\n"
        f"⚠ This may be a bug in video-censor-personal.\n"
        f"\n"
        f"Please report this issue at:\n"
        f"  https://github.com/justinfiore/video-censor-personal/issues\n"
        f"\n"
        f"Copy the following into the bug report form:\n"
        f"\n"
        f"Title: Bug: {phase} produced corrupt output ({error_summary})\n"
        f"\n"
        f"Description:\n"
        f"## What happened\n"
        f"During the {phase} step, video-censor-personal produced an intermediate\n"
        f"file that could not be read by the next processing step.\n"
        f"\n"
        f"Error: {first_three_lines}\n"
        f"Phase: {phase}\n"
        f"File: {file_path}\n"
        f"\n"
        f"## How to reproduce\n"
        f"Command: {command}\n"
        f"Config: {config_file}\n"
        f"Input: {input_file}\n"
        f"\n"
        f"## Environment\n"
        f"- ffmpeg version: {ffmpeg_version}\n"
        f"- OS: {os_info}\n"
        f"- Python: {python_version}\n"
        f"{separator}"
    )
